version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_DB: reddit_clone
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
volumes:
  postgres-data:
